package enums;

public enum Equipment {
    BARBELL,
    DUMBBELL,

    MACHINE,
    LEG_PRESS_MACHINE,
    LEG_EXTENSION_MACHINE,
    LEG_CURL_MACHINE,
    CALF_RAISE_MACHINE,
    PEC_DECK_MACHINE,
    LAT_PULLDOWN_MACHINE,
    ROW_MACHINE,

    CABLE,
    CABLE_MACHINE,

    SQUAT_RACK,
    SMITH_MACHINE,
    FLAT_BENCH,
    INCLINE_BENCH,
    DECLINE_BENCH,
    PREACHER_BENCH
}
