package model.enums;

// enum representing all equipment types
public enum Equipment {
    // FREE WEIGHTS
    BARBELL,
    EZ_BAR,
    DUMBBELL,
    KETTLEBELL,

    // BODYWEIGHT / STATION
    BODYWEIGHT,
    PULL_UP_BAR,
    DIP_STATION,

    // BENCHES / RACKS
    SQUAT_RACK,
    SMITH_MACHINE,
    FLAT_BENCH,
    INCLINE_BENCH,
    DECLINE_BENCH,
    PREACHER_BENCH,
    HYPEREXTENSION_BENCH,

    // CABLE
    CABLE,
    CABLE_MACHINE,

    // GENERAL MACHINE
    MACHINE,

    // CHEST MACHINES
    PEC_DECK_MACHINE,
    CHEST_PRESS_MACHINE,
    INCLINE_CHEST_PRESS_MACHINE,

    // BACK MACHINES
    LAT_PULLDOWN_MACHINE,
    ROW_MACHINE,
    SEATED_ROW_MACHINE,
    CHEST_SUPPORTED_ROW_MACHINE,
    T_BAR_ROW,

    // SHOULDER MACHINES
    SHOULDER_PRESS_MACHINE,
    LATERAL_RAISE_MACHINE,
    REAR_DELT_FLY_MACHINE,

    // ARM MACHINES
    MACHINE_PREACHER_CURL,
    MACHINE_BICEP_CURL,
    MACHINE_TRICEP_EXTENSION,
    MACHINE_DIP,

    // LEG MACHINES
    LEG_PRESS_MACHINE,
    LEG_EXTENSION_MACHINE,
    LEG_CURL_MACHINE,
    SEATED_LEG_CURL_MACHINE,
    LYING_LEG_CURL_MACHINE,
    CALF_RAISE_MACHINE,
    SEATED_CALF_RAISE_MACHINE,
    HACK_SQUAT_MACHINE,
    HIP_THRUST_MACHINE,
    HIP_ABDUCTION_MACHINE,
    HIP_ADDUCTION_MACHINE,
    GLUTE_KICKBACK_MACHINE,

    // CORE MACHINES
    AB_CRUNCH_MACHINE,
    ROTARY_TORSO_MACHINE,
}